---
- hosts: routers
  connection: local
  gather_facts: no

  tasks:
  - debug: var=inventory_hostname

  - include_role:
      name: ipam_check
      tasks_from: ip_check
    vars:
      ipam_check_IP: '{{ lookup("vars", item) }}'
    loop:
      - ntp_server
      - tunnel_ip

  - include_role:
      name: ipam_check
      tasks_from: subnet_check
    vars:
      ipam_check_ID: "{{ lookup('vars', item).split('_')[-1].split('.')[2] }}"
      ipam_check_DESCRIPTION: "{{ lookup('vars', item) }}"
    loop: 
      - mgmt_subnet

  - debug:
      msg: IP CHECK COMPLETE
    run_once: yes
